network:
  version: 2
  ethernets:
    ens3:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.64.101/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
      nameservers:
        addresses:
          - 77.88.8.8
          - 1.1.1.1
#      match:
#        macaddress: "52:54:00:36:34:47"
#      set-name: ens3
